-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Watermarker\watermark_ip_src_Bit_Divider.vhd
-- Created: 2022-05-12 17:01:48
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: watermark_ip_src_Bit_Divider
-- Source Path: Watermarker/watermarking/Indexing/Index Definer/Bit Divider Inner
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY watermark_ip_src_Bit_Divider IS
  PORT( in_rsvd                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        LSBs                              :   OUT   std_logic_vector(4 DOWNTO 0);  -- ufix5
        MSBs                              :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
        );
END watermark_ip_src_Bit_Divider;


ARCHITECTURE rtl OF watermark_ip_src_Bit_Divider IS

  -- Signals
  SIGNAL in_unsigned                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL LSBs_tmp                         : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL MSBs_tmp                         : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  in_unsigned <= unsigned(in_rsvd);

  LSBs_tmp <= in_unsigned(4 DOWNTO 0);

  LSBs <= std_logic_vector(LSBs_tmp);

  MSBs_tmp <= in_unsigned(7 DOWNTO 5);

  MSBs <= std_logic_vector(MSBs_tmp);

END rtl;

