SLStudio.Utils.RemoveHighlighting(get_param('Watermarker', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Watermarker', 'handle'));
annotate_port('gm_Watermarker/watermarking/Indexing', 0, 3, '');
annotate_port('gm_Watermarker/watermarking/Switch', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/delayMatch1', 1, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Inner', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/Counter Inner', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Inner', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/Counter Inner', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Outer', 1, 1, '');
annotate_port('Watermarker/watermarking/Indexing/Counter Outer', 1, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Outer', 1, 1, '');
annotate_port('Watermarker/watermarking/Indexing/Counter Outer', 1, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/HDL Counter', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/HDL Counter', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/HDL Counter', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/HDL Counter', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/Simple Dual Port RAM', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 1, 1, '');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 1, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 0, 1, '');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 1, 1, '');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 1, 1, '');
annotate_port('Watermarker/watermarking/Indexing/Simple Dual Port RAM', 0, 1, '');
