open_system('gm_Watermarker');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing', 0, 3, 'cp : 2.394 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Switch', 'user2');
annotate_port('gm_Watermarker/watermarking/Switch', 0, 1, 'cp : 3.077 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/delayMatch1', 'user1');
annotate_port('gm_Watermarker/watermarking/delayMatch1', 1, 1, 'cp : 3.319 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/Simple Dual Port RAM', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/Simple Dual Port RAM', 0, 1, 'cp : 2.394 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('Watermarker/watermarking/Indexing/Simple Dual Port RAM', 'user1');
annotate_port('Watermarker/watermarking/Indexing/Simple Dual Port RAM', 0, 1, 'cp : 2.394 ns');
