open_system('Watermarker');
open_system('gm_Watermarker');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/Counter Inner', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Inner', 0, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/Counter Inner', 'user2');
annotate_port('Watermarker/watermarking/Indexing/Counter Inner', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/Counter Inner', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Inner', 0, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/Counter Inner', 'user2');
annotate_port('Watermarker/watermarking/Indexing/Counter Inner', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/Counter Outer', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Outer', 1, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/Counter Outer', 'user2');
annotate_port('Watermarker/watermarking/Indexing/Counter Outer', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/Counter Outer', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/Counter Outer', 1, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/Counter Outer', 'user2');
annotate_port('Watermarker/watermarking/Indexing/Counter Outer', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/HDL Counter', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/HDL Counter', 0, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/HDL Counter', 'user2');
annotate_port('Watermarker/watermarking/Indexing/HDL Counter', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/HDL Counter', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/HDL Counter', 0, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/HDL Counter', 'user2');
annotate_port('Watermarker/watermarking/Indexing/HDL Counter', 0, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 1, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 'user2');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 0/Direct Lookup Table (n-D)', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 'user2');
annotate_port('gm_Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 1, 1, 'Block not characterized');
hilite_system('Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 'user2');
annotate_port('Watermarker/watermarking/Indexing/ROM Template 1/Direct Lookup Table (n-D)', 1, 1, 'Block not characterized');
