-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Watermarker\watermark_ip_addr_decoder.vhd
-- Created: 2022-05-03 00:49:47
-- 
-- Generated by MATLAB 9.12 and HDL Coder 3.20
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: watermark_ip_addr_decoder
-- Source Path: watermark_ip/watermark_ip_axi_lite/watermark_ip_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY watermark_ip_addr_decoder IS
  PORT( clk                               :   IN    std_logic;
        rstx                              :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_ip_timestamp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        read_pixel_out                    :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_axi_enable                  :   OUT   std_logic;  -- ufix1
        write_pixel_in                    :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        write_mes_in                      :   OUT   std_logic  -- ufix1
        );
END watermark_ip_addr_decoder;


ARCHITECTURE rtl OF watermark_ip_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_ip_timestamp_1_1      : std_logic;  -- ufix1
  SIGNAL const_0                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_ip_timestamp_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1_1                        : std_logic;  -- ufix1
  SIGNAL read_pixel_out_unsigned          : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL decode_sel_pixel_out_1_1         : std_logic;  -- ufix1
  SIGNAL read_reg_ip_timestamp            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_ip_timestamp_1_1       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_reg_pixel_out               : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_slice_pixel_out_1           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_pixel_out_1_1          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_axi_enable_1_1        : std_logic;  -- ufix1
  SIGNAL reg_enb_axi_enable_1_1           : std_logic;  -- ufix1
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_in_axi_enable               : std_logic;  -- ufix1
  SIGNAL data_reg_axi_enable_1_1          : std_logic;  -- ufix1
  SIGNAL decode_sel_pixel_in_1_1          : std_logic;  -- ufix1
  SIGNAL reg_enb_pixel_in_1_1             : std_logic;  -- ufix1
  SIGNAL data_in_pixel_in                 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL data_reg_pixel_in_1_1            : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL decode_sel_mes_in_1_1            : std_logic;  -- ufix1
  SIGNAL reg_enb_mes_in_1_1               : std_logic;  -- ufix1
  SIGNAL data_in_mes_in                   : std_logic;  -- ufix1
  SIGNAL data_reg_mes_in_1_1              : std_logic;  -- ufix1

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_ip_timestamp_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0002#, 14) ELSE
      '0';

  const_0 <= to_unsigned(0, 32);

  read_ip_timestamp_unsigned <= unsigned(read_ip_timestamp);

  const_1_1 <= '1';

  enb <= const_1_1;

  read_pixel_out_unsigned <= unsigned(read_pixel_out);

  
  decode_sel_pixel_out_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0042#, 14) ELSE
      '0';

  reg_ip_timestamp_process : PROCESS (clk, rstx)
  BEGIN
    IF rstx = '1' THEN
      read_reg_ip_timestamp <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_ip_timestamp <= read_ip_timestamp_unsigned;
      END IF;
    END IF;
  END PROCESS reg_ip_timestamp_process;


  
  decode_rd_ip_timestamp_1_1 <= const_0 WHEN decode_sel_ip_timestamp_1_1 = '0' ELSE
      read_reg_ip_timestamp;

  reg_pixel_out_process : PROCESS (clk, rstx)
  BEGIN
    IF rstx = '1' THEN
      read_reg_pixel_out <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        read_reg_pixel_out <= read_pixel_out_unsigned;
      END IF;
    END IF;
  END PROCESS reg_pixel_out_process;


  data_slice_pixel_out_1 <= resize(read_reg_pixel_out, 32);

  
  decode_rd_pixel_out_1_1 <= decode_rd_ip_timestamp_1_1 WHEN decode_sel_pixel_out_1_1 = '0' ELSE
      data_slice_pixel_out_1;

  data_read <= std_logic_vector(decode_rd_pixel_out_1_1);

  
  decode_sel_axi_enable_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0001#, 14) ELSE
      '0';

  reg_enb_axi_enable_1_1 <= decode_sel_axi_enable_1_1 AND wr_enb;

  data_write_unsigned <= unsigned(data_write);

  data_in_axi_enable <= data_write_unsigned(0);

  reg_axi_enable_1_1_process : PROCESS (clk, rstx)
  BEGIN
    IF rstx = '1' THEN
      data_reg_axi_enable_1_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_axi_enable_1_1 = '1' THEN
        data_reg_axi_enable_1_1 <= data_in_axi_enable;
      END IF;
    END IF;
  END PROCESS reg_axi_enable_1_1_process;


  
  decode_sel_pixel_in_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0040#, 14) ELSE
      '0';

  reg_enb_pixel_in_1_1 <= decode_sel_pixel_in_1_1 AND wr_enb;

  data_in_pixel_in <= data_write_unsigned(7 DOWNTO 0);

  reg_pixel_in_1_1_process : PROCESS (clk, rstx)
  BEGIN
    IF rstx = '1' THEN
      data_reg_pixel_in_1_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_pixel_in_1_1 = '1' THEN
        data_reg_pixel_in_1_1 <= data_in_pixel_in;
      END IF;
    END IF;
  END PROCESS reg_pixel_in_1_1_process;


  write_pixel_in <= std_logic_vector(data_reg_pixel_in_1_1);

  
  decode_sel_mes_in_1_1 <= '1' WHEN addr_sel_unsigned = to_unsigned(16#0041#, 14) ELSE
      '0';

  reg_enb_mes_in_1_1 <= decode_sel_mes_in_1_1 AND wr_enb;

  data_in_mes_in <= data_write_unsigned(0);

  reg_mes_in_1_1_process : PROCESS (clk, rstx)
  BEGIN
    IF rstx = '1' THEN
      data_reg_mes_in_1_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND reg_enb_mes_in_1_1 = '1' THEN
        data_reg_mes_in_1_1 <= data_in_mes_in;
      END IF;
    END IF;
  END PROCESS reg_mes_in_1_1_process;


  write_axi_enable <= data_reg_axi_enable_1_1;

  write_mes_in <= data_reg_mes_in_1_1;

END rtl;

